#!/bin/bash

if [ -z "$BB_ROOT" ]; then
    echo "Environment variable BB_ROOT required pointing to BlackBox installation directory"
else
    make -f Makefile.linux clean
    PWD=`pwd`
    wine "$BB_ROOT/BlackBox.exe" /USE "`winepath $PWD`" $* &
fi
